# Generated by Django 5.0.6 on 2024-07-24 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApi', '0067_alter_table_end_time_alter_table_start_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['Address', 'Name']},
        ),
        migrations.AlterField(
            model_name='table',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
